### ISSUE TITLE
Implement Responsive Navbar

### ISSUE THREAD

**Issue by KumaTelila** [pray3m/freelanceX#14]
I was looking at your project and I want to suggest you to make responsive navbar

and if you are willing to collabrate with me on I can contribute to you project 
![Oneplus-Nord-2-localhost](https://github.com/user-attachments/assets/aef0c66c-3b0f-4bd8-8a3d-46fde6568def)

**Comment by pray3m** [comment]
@KumaTelila  sure, you may contribute to the project!

**Comment by f0rsakeN-afk** [comment]
May i contribute on it?

**Comment by pray3m** [comment]
sure, go ahead !
